# Generated by Django 3.0.7 on 2022-07-15 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0005_auto_20220715_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
