# Generated by Django 4.0.5 on 2022-07-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0011_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinestore.customer'),
        ),
    ]
