# Generated by Django 4.0.5 on 2022-07-18 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinestore', '0017_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('shipping_country', models.CharField(max_length=200, null=True)),
                ('shipping_address', models.CharField(max_length=200, null=True)),
                ('shipping_city', models.CharField(max_length=200, null=True)),
                ('shipping_zipcode', models.CharField(max_length=200, null=True)),
                ('shipping_county', models.CharField(max_length=200, null=True)),
                ('shipping_town', models.CharField(max_length=200, null=True)),
                ('payment_method', models.CharField(max_length=200, null=True)),
                ('payment_data', models.CharField(max_length=200, null=True)),
                ('payment_complete', models.BooleanField(default=False)),
                ('order_complete', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
