# Generated by Django 4.0.5 on 2022-07-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0020_alter_cart_total_alter_cartitems_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='total',
        ),
    ]
