# Generated by Django 4.0.5 on 2022-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0025_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
